CREATE DATABASE IF NOT EXISTS artbox CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE artbox;

CREATE TABLE IF NOT EXISTS oeuvres (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titre VARCHAR(255) NOT NULL,
    artiste VARCHAR(255) NOT NULL,
    description TEXT,
    image VARCHAR(500)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
